name: GaSmart
description: TODO

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  flutter_native_splash: ^2.3.6
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  http: ^1.1.2
  fl_chart: ^0.65.0
  month_year_picker: ^0.3.0+1
  localstorage: ^4.0.1+4
  flutter_markdown: ^0.6.18+3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
